### ISSUE TITLE
Development environment?

### ISSUE THREAD

**Issue by GuiguiSurLinux** [PGSSoft/PrestigeModel#1]
Hi! Thanks for making the game :)

What kind of dev environment are you using? I want to make a better bot but it's been a while since I used Java.

Thanks!

**Comment by tomekziel** [comment]
There is no IDE-specific files in this repo. You may pick your preferred tool, like Eclipse or IntelliJ, import Java sources (along with gson dependency) and develop. There is an arena class for bot fights, you may test how your bot compares to existing ones in series of games.

**Comment by GuiguiSurLinux** [comment]
Thanks for replying. Do you have any clues as to the required JRE version and/or other dependencies? I can't seem to get anything working under JRE 1.7.

**Comment by GuiguiSurLinux** [comment]
I ended up using Android Studio. It wasn't really necessary but it made the debugging easier.

For anyone else who stumbles into this and just wants to run the Arena:
- You probably have some error about packages:
  - Put the java folder in the source path (in Android Studio, declare as source).
  - Put model's java folder in the source path as well (there are dependencies).
- You probably have some error about gson:
  - Download the gson dependency from here: http://search.maven.org/#artifactdetails|com.google.code.gson|gson|2.3.1|jar (or latest one)
  - Create a lib folder in the project root.
  - Put gson-2.3.1.jar in lib folder.
  - Add gson as a library (by right-clicking).

That should be about it. You can run Arena by right-clicking on the file and selecting Run 'Main.main()'.
